### ISSUE TITLE
installation script fails when having multiple profiles in firefox

### ISSUE THREAD

**Issue by dreisss** [dxdotdev/arc-ui#10]
**Describe the bug**
I tried to run the install script but had issues when having multiple profiles

**To Reproduce**
1. Create another profile in Firefox
2. Run the installation script

**Expected behavior**
Install configs to both profiles

**Comment by kunzaatko** [comment]
```
$ grep 'Path' ~/.mozilla/firefox/profiles.ini                                                                                                                                                           19:03:41
Path=49l2xdsk.default-1724678170536
Path=i269gcpi.default-release
Path=ymi9xbrf.default-nightly
Path=tyfm48xg.dev-edition-default
```
The solution would be to take the first, which is the default.
